const $ = (id) => document.getElementById(id);

const SECTION_ORDER = [
  'MOTIVO DE LA CONSULTA','PSQ GUARDIA','ALERGIAS / RAM','ANTECEDENTES PERSONALES SOMÁTICOS','ANTECEDENTES PERSONALES EN SALUD MENTAL','ANTECEDENTES FAMILIARES PSIQUIÁTRICOS','SITUACIÓN SOCIOFAMILIAR','HÁBITOS TÓXICOS','TRATAMIENTO HABITUAL','ENFERMEDAD ACTUAL','INTERVENCIÓN','EXPLORACIÓN PSICOPATOLÓGICA','ORIENTACIÓN DIAGNÓSTICA','PLAN TERAPÉUTICO','TRATAMIENTO ACTUAL'
];

const ROUTES = {
  'PSQ GUARDIA':['urgencias','psiquiatra de guardia','guardia','pediatría','alta','vigilancia familiar','retirar medicación','volver a urgencias'],
  'ALERGIAS / RAM':['alergia','alérgica','amoxicilina','habones','reacción adversa','efecto adverso','akatisia','inquietud tremenda','aripiprazol'],
  'ANTECEDENTES PERSONALES SOMÁTICOS':['nació','nacimiento','parto','término','desarrollo','caminó','habló','vacunas','bronquitis','asma','apendicitis','operaron','migraña','hierro','anemia','menarquia','convulsiones','traumatismo','neurológica','reglas'],
  'ANTECEDENTES PERSONALES EN SALUD MENTAL':['psicóloga','psicólogo','salud mental','usmij','unidad de salud mental','seguimiento','ingreso psiquiátrico','ingresos psiquiátricos','crisis de ansiedad','acoso escolar','autolesiones anteriores','cortes anteriores','urgencias por cortes','intento de suicidio previo','aripiprazol'],
  'ANTECEDENTES FAMILIARES PSIQUIÁTRICOS':['antecedentes psiquiátricos en la familia','abuela','abuelo','tío','tía','padre','madre','hermano','hermana','familiar','trastorno bipolar','depresión','ataques de pánico','alcoholismo','problemas con el alcohol','psicosis','esquizofrenia','suicidio'],
  'SITUACIÓN SOCIOFAMILIAR':['vive','vivo','casa','padres separados','separados','padre vive','relación con','instituto','bachillerato','tutora','estudios','faltado','acoso','amiga','amigo','marta','irene','novio','ex','pareja','violencia','servicios sociales','fuga','se fue de casa','hermano vive','trabajo','diseño','bellas artes'],
  'HÁBITOS TÓXICOS':['vapeo','vapea','nicotina','tabaco','alcohol','cannabis','porro','porros','cocaína','anfetamina','mdma','ketamina','benzodiacepina','lorazepam sin','bebidas energéticas','sustancia'],
  'TRATAMIENTO HABITUAL':['sertralina','melatonina','pastillero','toma todos los días','se le olvida','adherencia','hierro','ibuprofeno','tratamiento habitual','medicación habitual'],
  'ENFERMEDAD ACTUAL':['últimas semanas','últimos días','últimos meses','desde verano','desde julio','desde agosto','seis semanas','dos meses','ayer','domingo','esta semana','peor','triste','vacía','lloro','no siento nada','menos ganas','aislada','encerrada','sueño','duermo','dormir','apetito','peso','concentración','cansancio','culpa','decepciono','ansiedad','pánico','autolesión','cortes','morir','matar','pastillas','ideación','plan','agobio','no puedo más','rendimiento','faltar a clase'],
  'INTERVENCIÓN':['plan de seguridad','medida temporal de seguridad','medicación debe seguir inaccesible','organizar presencia familiar','coordinación con','hablado de algunas cosas','familia debe','retirar objetos','control de un adulto'],
  'EXPLORACIÓN PSICOPATOLÓGICA':['sabes dónde estamos','qué día es hoy','consciente','orientada','orientado','voces','oye voces','escucha voces','ve cosas','eufórica','mucha energía','impulsiva','rituales','pensamientos repetitivos','pesadillas','recuerdos intrusivos','ideación suicida actual','intención de hacerte daño','plan pensado','riesgo heteroagresivo'],
  'ORIENTACIÓN DIAGNÓSTICA':['orientación provisional','estamos ante','cuadro depresivo','depresivo clínicamente','ansiedad asociada','autolesiones no suicidas','consumo de cannabis','episodio maníaco','cuadro psicótico','diagnóstica provisional','diagnóstico provisional'],
  'PLAN TERAPÉUTICO':['mi indicación','mantener sertralina','no vamos a subir','reducir','suspender cannabis','reducir bebidas','evitar alcohol','retomar psicoterapia','revisión psiquiátrica','acudís a urgencias','seguimiento','coordinar con','administración supervisada'],
  'TRATAMIENTO ACTUAL':['mantener sertralina','melatonina por la noche','administración supervisada','tratamiento actual','indico','pautamos','pauta']
};

const FAMILY_RELATIONS=['madre','padre','abuela','abuelo','tío','tía','hermano','hermana','primo','prima','familiar'];
const PSYCH_FAMILY_TERMS=['depresión','bipolar','psicosis','esquizofrenia','ansiedad','pánico','alcohol','adicción','suicid'];
const IRRELEVANT_NONFAMILY=['amiga','amigo','vecina','vecino','compañero de trabajo','hija de una vecina','hijo con tdah','marta'];

const demoText=`PSIQUIATRA: Lucía, cuéntame por qué estamos hoy aquí.\nPACIENTE: Porque mi madre se ha asustado. Ayer me hice unos cortes en el antebrazo después de discutir con ella. No quería morirme, quería dejar de sentirme tan agobiada.\nMADRE: Lleva unas seis semanas peor, más encerrada, faltando al instituto, durmiendo fatal y diciendo que no puede más.\nHERMANO: También fuma cannabis bastante más de lo que dice. Desde verano casi a diario algunas semanas.\nPSIQUIATRA: ¿Antecedentes psiquiátricos familiares?\nMADRE: Una vecina tiene una hija con anorexia y una amiga mía tiene un hijo con TDAH.\nHERMANO: Eso no es familia. La abuela materna tuvo depresión y el tío paterno tiene trastorno bipolar con ingresos.\nPACIENTE: Yo tomo sertralina 50 mg, aunque últimamente se me olvida algunos días.\nMADRE: Algunos días no; diría que la toma cuatro días de siete.\nPSIQUIATRA: ¿Alergias?\nMADRE: Con amoxicilina tuvo habones de pequeña. Y con aripiprazol tuvo mucha inquietud y se lo retiraron.\nPSIQUIATRA: ¿Antecedentes médicos?\nMADRE: Nació a término, desarrollo normal, apendicitis alrededor de los once o doce años y migrañas ocasionales.\nPSIQUIATRA: ¿Cómo estás ahora?\nPACIENTE: Me siento vacía, duermo muy tarde, tengo menos apetito, estoy cansada y no me concentro. A veces pienso que mi madre estaría mejor sin mí, pero ahora mismo no tengo intención ni plan de suicidarme.\nPSIQUIATRA: ¿Sabes dónde estamos y qué día es hoy?\nPACIENTE: Sí, estamos en Salud Mental y hoy es jueves.\nPSIQUIATRA: ¿Oyes voces o ves cosas que otros no?\nPACIENTE: No.\nPSIQUIATRA: Como orientación provisional, estamos ante un cuadro depresivo clínicamente significativo con ansiedad asociada y autolesiones no suicidas. Mantendremos sertralina 50 mg por la mañana con supervisión, melatonina por la noche, reducción y preferiblemente suspensión de cannabis, psicoterapia y revisión en una semana.`;

const state={analyzed:false,sections:{},sources:[],missing:[],conflicts:[],alerts:[],report:''};

function normalize(text){return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function speakerLabel(raw){const s=normalize(raw||'');if(s.includes('psiquiat'))return'Psiquiatra';if(s.includes('paciente')||s.includes('lucia'))return'Paciente';if(s.includes('madre'))return'Madre';if(s.includes('hermano'))return'Hermano';if(s.includes('padre'))return'Padre';return raw?raw.trim():'No identificado'}
function splitIntoTurns(text){const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),turns=[];let current=null;for(const line of lines){const m=line.match(/^([A-ZÁÉÍÓÚÜÑ ]{2,25}):\s*(.*)$/i);if(m){current={speaker:speakerLabel(m[1]),text:m[2].trim()};turns.push(current)}else if(current){current.text+=' '+line}else turns.push({speaker:'No identificado',text:line})}return turns}
function splitSentences(text){return text.split(/(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÜÑ0-9¿])|;\s+/).map(s=>s.trim()).filter(s=>s.length>2)}
function hasAny(text,terms){const n=normalize(text);return terms.some(t=>n.includes(normalize(t)))}
function familyPsychRelevant(sentence){const n=normalize(sentence),hasRelation=FAMILY_RELATIONS.some(x=>n.includes(normalize(x))),hasPsych=PSYCH_FAMILY_TERMS.some(x=>n.includes(normalize(x))),clearlyNonFamily=IRRELEVANT_NONFAMILY.some(x=>n.includes(normalize(x)))&&!hasRelation;return hasRelation&&hasPsych&&!clearlyNonFamily}
function scoreRoute(section,sentence,speaker){const n=normalize(sentence);let score=0;for(const term of ROUTES[section]||[])if(n.includes(normalize(term)))score+=2;if(section==='ANTECEDENTES FAMILIARES PSIQUIÁTRICOS'){if(!familyPsychRelevant(sentence))return 0;score+=5}if(section==='EXPLORACIÓN PSICOPATOLÓGICA'&&speaker==='Psiquiatra')score+=1;if(['ORIENTACIÓN DIAGNÓSTICA','PLAN TERAPÉUTICO','INTERVENCIÓN','TRATAMIENTO ACTUAL'].includes(section)&&speaker!=='Psiquiatra')score-=2;if(section==='ENFERMEDAD ACTUAL'&&/hace anos|de pequena|cuando tenia|el ano pasado|desde los trece|2024/.test(n))score-=3;if(section==='ANTECEDENTES PERSONALES EN SALUD MENTAL'&&/ayer|esta semana|ahora mismo|ultimas semanas/.test(n))score-=2;return Math.max(score,0)}
function chooseRoute(sentence,speaker,turnIndex,totalTurns){const candidates=Object.keys(ROUTES).map(section=>({section,score:scoreRoute(section,sentence,speaker)})).sort((a,b)=>b.score-a.score),top=candidates[0];if(!top||top.score<2)return null;const n=normalize(sentence);if(speaker==='Psiquiatra'&&/por que estamos|por que habeis venido|motivo/.test(n))return null;if(turnIndex<Math.min(10,totalTurns)&&speaker!=='Psiquiatra'&&/cortes|urgencias|autoles|ha traido|estamos aqui|asustado|asustada|ayer/.test(n))return'MOTIVO DE LA CONSULTA';return top.section}
function clinicalVerb(speaker,text,index){const n=normalize(text);if(speaker==='Paciente'){if(/niega|no tengo|no queria|no he/.test(n))return'niega';if(/reconozco|reconoce|alguna vez|probablemente|fumo mas/.test(n))return'reconoce';return['refiere','explica','comenta','describe','señala'][index%5]}if(speaker==='Madre')return['informa','explica','comunica','señala','comenta'][index%5];if(speaker==='Hermano')return['señala','explica','comenta','informa'][index%4];if(speaker==='Padre')return['informa','explica','señala','comenta'][index%4];return'se recoge'}
function cleanSentence(sentence){return sentence.replace(/^bueno,?\s*/i,'').replace(/^pues\s*/i,'').trim()}
function attributed(item,index){const s=item.speaker,txt=cleanSentence(item.text);if(s==='Psiquiatra')return txt;const subject=s==='Paciente'?'La paciente':s==='Madre'?'La madre':s==='Hermano'?'El hermano':s==='Padre'?'El padre':'Durante la entrevista',verb=clinicalVerb(s,txt,index),lower=txt.charAt(0).toLowerCase()+txt.slice(1);if(verb==='niega'&&/^no\b/i.test(txt))return`${subject} niega ${lower.replace(/^no\s+/i,'')}`;return`${subject} ${verb} que ${lower}`}
function dedupeItems(items){const seen=new Set();return items.filter(item=>{const key=normalize(item.text).replace(/[^a-z0-9 ]/g,'').slice(0,100);if(!key||seen.has(key))return false;seen.add(key);return true})}

function buildSections(turns){const sections=Object.fromEntries(SECTION_ORDER.map(s=>[s,[]]));turns.forEach((turn,turnIndex)=>{splitSentences(turn.text).forEach(sentence=>{const route=chooseRoute(sentence,turn.speaker,turnIndex,turns.length);if(route)sections[route].push({speaker:turn.speaker,text:sentence,turnIndex})})});if(!sections['MOTIVO DE LA CONSULTA'].length){sections['MOTIVO DE LA CONSULTA']=turns.slice(0,8).filter(t=>t.speaker!=='Psiquiatra'&&hasAny(t.text,['urgencias','cortes','autoles','ha traído','ha traido','asustada','ayer','consulta'])).slice(0,3).map((t,i)=>({speaker:t.speaker,text:t.text,turnIndex:i}))}const forbidden=[...ROUTES['ANTECEDENTES PERSONALES SOMÁTICOS'],...ROUTES['ANTECEDENTES PERSONALES EN SALUD MENTAL'],...ROUTES['ANTECEDENTES FAMILIARES PSIQUIÁTRICOS'],...ROUTES['HÁBITOS TÓXICOS'],...ROUTES['TRATAMIENTO HABITUAL']];sections['ENFERMEDAD ACTUAL']=sections['ENFERMEDAD ACTUAL'].filter(x=>!hasAny(x.text,forbidden)||hasAny(x.text,['ayer','ahora','últimas','ultimas','semanas','meses','desde verano','sueño','apetito','concentración','cansancio','ansiedad','morir','matar','cortes']));for(const key of SECTION_ORDER)sections[key]=dedupeItems(sections[key]).slice(0,key==='ENFERMEDAD ACTUAL'?12:10);return sections}
function detectSources(turns){return[...new Set(turns.map(t=>t.speaker).filter(s=>s!=='Psiquiatra'&&s!=='No identificado'))]}
function findTopic(turns,terms){return turns.filter(t=>hasAny(t.text,terms))}
function detectConflicts(turns){const out=[],suicide=findTopic(turns,['morir','matar','suicid','pastillas','no queria morirme','no tengo intención','no tengo intencion']);if(suicide.some(x=>/no queria|no tengo|niega|no iba a hacerlo/i.test(normalize(x.text)))&&suicide.some(x=>/dijo|ojala|pastillas|podia tomarse|abri el cajon/i.test(normalize(x.text))))out.push('Existen versiones y momentos diferentes respecto a ideación suicida y acceso a medicación. Deben conservarse la negación de intención actual y los episodios recientes de mayor aproximación al riesgo.');const cannabis=findTopic(turns,['cannabis','porro','porros','fumo']);if(cannabis.length>=2&&new Set(cannabis.map(x=>x.speaker)).size>1)out.push('La frecuencia de consumo de cannabis es descrita de forma distinta por la paciente y los familiares; debe reflejarse la versión más precisa sin ocultar la discrepancia.');const meds=findTopic(turns,['sertralina','pastillero','se me olvida','toma todos los dias','cuatro dias','tres dias igual']);if(meds.length>=2&&new Set(meds.map(x=>x.speaker)).size>1)out.push('Existe discrepancia sobre la adherencia al tratamiento habitual; la paciente y los familiares aportan estimaciones distintas.');const appendix=findTopic(turns,['apendicitis','once','doce']);if(appendix.some(x=>/once/.test(normalize(x.text)))&&appendix.some(x=>/doce/.test(normalize(x.text))))out.push('La edad exacta de la apendicectomía no queda consensuada (11-12 años); no debe inventarse una fecha exacta.');return out}
function detectAlerts(turns){const all=normalize(turns.map(t=>t.text).join(' ')),alerts=[];if(/cortes|autoles/.test(all))alerts.push('Autolesiones recientes o repetidas.');if(/morir|matar|suicid|pastillas/.test(all))alerts.push('Ideación de muerte/suicida o referencia a posible método: requiere revisión clínica explícita.');if(/cannabis|porro/.test(all))alerts.push('Consumo de cannabis relevante para la valoración clínica.');if(/no puedo dormir|duermo|sueno|insomnio/.test(all))alerts.push('Alteración significativa del sueño.');if(/agres|empuj|punetazo/.test(all))alerts.push('Conductas de agresividad/impulsividad referidas: revisar riesgo hacia terceros y entorno.');return alerts}
function detectMissing(sections){const missing=[],must=['ALERGIAS / RAM','ANTECEDENTES PERSONALES SOMÁTICOS','ANTECEDENTES PERSONALES EN SALUD MENTAL','ANTECEDENTES FAMILIARES PSIQUIÁTRICOS','SITUACIÓN SOCIOFAMILIAR','HÁBITOS TÓXICOS','TRATAMIENTO HABITUAL','EXPLORACIÓN PSICOPATOLÓGICA'];must.forEach(k=>{if(!sections[k]||!sections[k].length)missing.push(`${k}: no consta información suficiente en la entrevista.`)});return missing}
function relevantOpeningSummary(sections){const pool=[...(sections['MOTIVO DE LA CONSULTA']||[]),...(sections['ENFERMEDAD ACTUAL']||[])].filter(x=>hasAny(x.text,['cortes','autoles','peor','urgencias','ansiedad','triste','vacía','vacia','dormir','apetito','instituto','morir','matar']));return dedupeItems(pool).slice(0,4)}
function renderSectionText(section,items){if(!items||!items.length)return'No consta información suficiente en la entrevista aportada.';let chosen=items;if(section==='MOTIVO DE LA CONSULTA')chosen=relevantOpeningSummary(state.sections).slice(0,3);if(section==='ENFERMEDAD ACTUAL')chosen=items.slice(0,9);if(['ORIENTACIÓN DIAGNÓSTICA','PLAN TERAPÉUTICO','INTERVENCIÓN','TRATAMIENTO ACTUAL'].includes(section))return chosen.map(x=>cleanSentence(x.text)).join(' ');return chosen.map((x,i)=>attributed(x,i)).join(' ')}
function buildReport(sections){return SECTION_ORDER.map(section=>`${section}\n${renderSectionText(section,sections[section])}`).join('\n\n')}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[ch]))}
function renderList(id,values){$(id).innerHTML=values.length?values.map(v=>`<li>${escapeHtml(v)}</li>`).join(''):'<li>No se han detectado elementos.</li>'}
function renderRouting(sections){$('routingGrid').innerHTML=SECTION_ORDER.map(section=>{const items=sections[section]||[],preview=items.slice(0,2).map(x=>cleanSentence(x.text)).join(' · ')||'Sin información clasificada';return`<article class="route-card ${items.length?'active':''}"><div class="route-head"><h3>${escapeHtml(section)}</h3><span class="route-count">${items.length}</span></div><p class="route-preview">${escapeHtml(preview)}</p></article>`}).join('')}

function analyze(){const text=$('caseText').value.trim();if(!text){$('sessionMessage').textContent='Pega primero una entrevista ficticia o anonimizada.';return}const turns=splitIntoTurns(text),sections=buildSections(turns);state.sections=sections;state.sources=detectSources(turns);state.conflicts=detectConflicts(turns);state.alerts=detectAlerts(turns);state.missing=detectMissing(sections);state.report=buildReport(sections);state.analyzed=true;$('sourcesList').innerHTML=state.sources.length?state.sources.map(s=>`<span class="tag">${escapeHtml(s)}</span>`).join(''):'<span class="tag">No identificadas</span>';renderList('missingList',state.missing);renderList('conflictList',state.conflicts);renderList('alertList',state.alerts);renderRouting(sections);$('reportEditor').textContent=state.report;$('validateCheck').checked=false;$('copyReport').disabled=true;showScreen('review')}
function wipeTransientState(message='Sesión destruida. No queda contenido clínico en la interfaz.'){$('caseText').value='';$('sourcesList').innerHTML='';$('missingList').innerHTML='';$('conflictList').innerHTML='';$('alertList').innerHTML='';$('routingGrid').innerHTML='';$('reportEditor').textContent='';$('validateCheck').checked=false;$('copyReport').disabled=true;Object.assign(state,{analyzed:false,sections:{},sources:[],missing:[],conflicts:[],alerts:[],report:''});$('sessionMessage').textContent=message;showScreen('input')}
function showScreen(name){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));const target=$(`screen-${name}`);if(target)target.classList.add('active');document.querySelectorAll('.step').forEach(el=>el.classList.toggle('active',el.dataset.step===name));if(name==='report'&&state.analyzed)$('reportEditor').textContent=buildReport(state.sections);window.scrollTo({top:0,behavior:'smooth'})}

$('loadDemo').addEventListener('click',()=>{$('caseText').value=demoText;$('sessionMessage').textContent=''});
$('analyzeCase').addEventListener('click',analyze);
$('recordButton').addEventListener('click',()=>alert('La captura real de audio permanece bloqueada en V0.3. En esta fase se valida primero la organización clínica del texto.'));
$('destroyInput').addEventListener('click',()=>wipeTransientState());
$('destroySession').addEventListener('click',()=>wipeTransientState());
$('validateCheck').addEventListener('change',e=>{$('copyReport').disabled=!e.target.checked});
$('copyReport').addEventListener('click',async()=>{if(!$('validateCheck').checked)return;const text=$('reportEditor').innerText;try{await navigator.clipboard.writeText(text);$('sessionMessage').textContent='Informe copiado tras validación clínica.'}catch{$('sessionMessage').textContent='No se pudo copiar automáticamente; selecciona el texto manualmente.'}});
document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>showScreen(btn.dataset.go)));
document.querySelectorAll('.step').forEach(btn=>btn.addEventListener('click',()=>{const step=btn.dataset.step;if((step==='review'||step==='report')&&!state.analyzed)return;showScreen(step)}));
window.addEventListener('pagehide',()=>{state.sections={};state.report=''})